METERED_USERNAME="f1ebf2716febef40f7bec5bc"

METERED_CREDENTIAL="Eh3e2MX5GtKBkcpX"

STUN_URL="stun:stun.relay.metered.ca:80"

TURN_URL="turn:standard.relay.metered.ca:80"

TURN_TLS_URL="turns:standard.relay.metered.ca:443?transport=tcp"